name: Python Test Coverage Report

on:
  workflow_run:
    workflows: ["Python Test Coverage"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  python-test-coverage-report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].number != null
    continue-on-error: false
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Download coverage report
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          name: python-test-coverage-report
          path: ./python
      - name: Display structure of downloaded files
        run: ls
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@v1.1.57
        with:
          github-token: ${{ github.token }}
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          pytest-xml-coverage-path: python/python-coverage.xml
          title: "Python Test Coverage Report"
          badge-title: "Python Test Coverage"
          default-branch: "main"
          report-only-changed-files: true
